name: untisplus
description: "A Flutter application for displaying school schedules and related information, designed to provide a user-friendly interface for students and teachers to access their timetables, homework, and other school-related data."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  google_fonts: ^8.0.2
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  flutter_markdown: ^0.7.1
  dynamic_color: ^1.8.1
  flutter_launcher_icons: ^0.14.4
  
  cupertino_icons: ^1.0.8
  simple_animations: ^5.2.0
  home_widget: ^0.9.0
  flutter_local_notifications: ^21.0.0
  timezone: ^0.11.0
  workmanager: ^0.9.0+3
  url_launcher: ^6.3.2
  file_picker: ^10.3.10
  image_picker: ^1.2.1
  google_generative_ai: ^0.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FEF7FF"
  adaptive_icon_foreground: "assets/icon.png"